In [2]:
import pandas as pd

# Data Exploration and Processing

### Loading Complaints Data

In [3]:
# Loading complaints data
df_complaints = pd.read_csv("SRDataset_w_zipcode.csv")

In [4]:
# Checking complaints data got loaded adequately
df_complaints.shape
# 3,864,047 rows and 15 columns

(3864047, 15)

In [5]:
# Exploring complaints data
df_complaints.head()

,Unique Key,Created Date,Closed Date,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Incident Zip,City,Status,Resolution Description,Resolution Action Updated Date,Borough,Latitude,Longitude
0,69197623,06/01/2026 02:07:09 PM,06/01/2026 02:16:05 PM,New York City Police Department,Illegal Parking,Blocked Sidewalk,NaN,11103.0,ASTORIA,Closed,The New York City Police Department responded ...,06/01/2026 02:16:08 PM,QUEENS,40.769581,-73.915593
1,69207017,06/01/2026 02:07:00 PM,06/01/2026 02:07:00 PM,Department of Environmental Protection,Water System,Hydrant Running (WC3),WC3,11209.0,BROOKLYN,Closed,The Department of Environmental Protection det...,06/01/2026 02:07:00 PM,BROOKLYN,40.624393,-74.038340
2,69205534,06/01/2026 02:06:58 PM,06/01/2026 02:06:58 PM,Department of Buildings,Building/Use,No Certificate Of Occupancy/Illegal/Contrary T...,NaN,10456.0,BRONX,Open,Your Service Request has been submitted to the...,06/01/2026 12:00:00 AM,BRONX,40.833781,-73.913806
3,69198329,06/01/2026 02:06:52 PM,06/01/2026 02:43:43 PM,New York City Police Department,Illegal Parking,Blocked Bike Lane,NaN,11205.0,BROOKLYN,Closed,The New York City Police Department responded ...,06/01/2026 02:43:47 PM,BROOKLYN,40.697416,-73.956717
4,69196443,06/01/2026 02:06:51 PM,06/01/2026 04:50:30 PM,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,10026.0,NEW YORK,Closed,The New York City Police Department responded ...,06/01/2026 04:50:33 PM,MANHATTAN,40.802451,-73.946622


***This dataset is from open NYC data on 311 service requests between June 1 2025 - June 1 2026***

**The variables we have:**

***When***
- when the complaint was created(Month/Date/Year Hour:Minutes:Seconds AM / PM)
- when the complaint was closed (Month/Date/Year Hour:Minutes:Seconds AM / PM)

***What***
- what the complaint was (this include problem, problem detail, additional details)

***Where***
- which borough the complaint came from
- which city the complaint came from (which is the same as borough, largely)
- exact latitude and longitude of complaint
- which zip code the complaint came from (this is for merging with income data)

***Response***
- Status (values include -> )
- If resolved, when did it get updated in the dataset
- What happened in the resolution

***Misc***
- unique key of each complaint (each row = one complaint)
- Agency to which it was submitted to

In [6]:
# Exploring complaints data
df_complaints.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency Name',
       'Problem (formerly Complaint Type)',
       'Problem Detail (formerly Descriptor)', 'Additional Details',
       'Incident Zip', 'City', 'Status', 'Resolution Description',
       'Resolution Action Updated Date', 'Borough', 'Latitude', 'Longitude'],
      dtype='str')

In [7]:
# Renaming column names
df_complaints = df_complaints.rename(
    columns = {
        'Problem (formerly Complaint Type)' : 'complaint',
        'Problem Detail (formerly Descriptor)' : 'complaint_detail',
        'Additional Details' : 'complaint_add_detail',
        'Unique Key': 'unique_key',
        'Created Date': 'created_date',
        'Closed Date': 'closed_date',
        'Agency Name': 'agency_name',
        'Due Date': 'due_date',
        'Resolution Description': 'resol_descrip',
        'Resolution Action Updated Date': 'resol_upd_date',
        'Status': 'status',
        'Borough': 'borough',
        'Latitude': 'latitude',
        'Longitude': 'longitude',
        'Incident Zip': 'zip',
        'City': 'city',
    }
)

In [8]:
#checking all columns got correctly renamed
df_complaints.columns

Index(['unique_key', 'created_date', 'closed_date', 'agency_name', 'complaint',
       'complaint_detail', 'complaint_add_detail', 'zip', 'city', 'status',
       'resol_descrip', 'resol_upd_date', 'borough', 'latitude', 'longitude'],
      dtype='str')

### Loading Income Data

In [9]:
df_income = pd.read_csv("income_data.csv")

In [10]:
# Checking income data got loaded adequately
df_income.shape
# 1825 rows and 5 columns (NY State has roughly ~1800 zipcodes, so should be fine)

(1825, 5)

In [11]:
# Exploring income_data.csv data
df_income.head()

,GEO_ID,NAME,B19013_001E,B19013_001M,Unnamed: 4
0,Geography,Geographic Area Name,Estimate!!Median household income in the past ...,Margin of Error!!Median household income in th...,NaN
1,860Z200US06390,ZCTA5 06390,98125,59611,NaN
2,860Z200US10001,ZCTA5 10001,129852,25244,NaN
3,860Z200US10002,ZCTA5 10002,48386,4836,NaN
4,860Z200US10003,ZCTA5 10003,154262,10754,NaN


In [12]:
# renaming column names
df_income = df_income.rename(columns =
    {'B19013_001E': 'median_hh_income',
    }
)

df_income

,GEO_ID,NAME,median_hh_income,B19013_001M,Unnamed: 4
0,Geography,Geographic Area Name,Estimate!!Median household income in the past ...,Margin of Error!!Median household income in th...,NaN
1,860Z200US06390,ZCTA5 06390,98125,59611,NaN
2,860Z200US10001,ZCTA5 10001,129852,25244,NaN
3,860Z200US10002,ZCTA5 10002,48386,4836,NaN
4,860Z200US10003,ZCTA5 10003,154262,10754,NaN
...,...,...,...,...,...
1820,860Z200US14898,ZCTA5 14898,58824,6860,NaN
1821,860Z200US14901,ZCTA5 14901,40989,3514,NaN
1822,860Z200US14903,ZCTA5 14903,67012,7191,NaN
1823,860Z200US14904,ZCTA5 14904,53174,5408,NaN


### Population Data

In [13]:
df_pop = pd.read_csv("pop_data.csv")

In [14]:
# Checking population data got loaded adequately
df_pop.shape
# 1825 rows and 5 columns (NY State has roughly ~1800 zipcodes, so should be fine)

(1825, 5)

In [15]:
# Exploring population data
df_pop.head()

,GEO_ID,NAME,B01003_001E,B01003_001M,Unnamed: 4
0,Geography,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,NaN
1,860Z200US06390,ZCTA5 06390,72,43,NaN
2,860Z200US10001,ZCTA5 10001,30511,1797,NaN
3,860Z200US10002,ZCTA5 10002,76873,3494,NaN
4,860Z200US10003,ZCTA5 10003,53560,2107,NaN


In [16]:
# renaming column names
df_pop = df_pop.rename(columns =
    {'B01003_001E': 'pop',
    }
)

## Merging Datasets

### Merging Income and Complaints Data

### Ensuring merge compatibility

In [17]:
# Income data: extract ZIP from "ZCTA5 10001" and checking adequate extraction
df_income["zip"] = df_income["NAME"].str.split().str[-1] #splitting string, getting last part of the string, and putting it in a new column called zip
df_income.head()

,GEO_ID,NAME,median_hh_income,B19013_001M,Unnamed: 4,zip
0,Geography,Geographic Area Name,Estimate!!Median household income in the past ...,Margin of Error!!Median household income in th...,NaN,Name
1,860Z200US06390,ZCTA5 06390,98125,59611,NaN,06390
2,860Z200US10001,ZCTA5 10001,129852,25244,NaN,10001
3,860Z200US10002,ZCTA5 10002,48386,4836,NaN,10002
4,860Z200US10003,ZCTA5 10003,154262,10754,NaN,10003


**--> Ensuring data types of column zip in both datasets are same**

In [18]:
# checking data type of zip in income data
df_income['zip'].dtype
# object/string

dtype('O')

In [19]:
# checking data type of zip in income data
df_complaints['zip'].dtype
# float64

dtype('float64')

In [20]:
# converting zip in complaints data to an integer first to remove decimal and then to string (given zip is not an actual number, I am keeping it as a string)
df_complaints["zip"] = df_complaints['zip'].astype("Int64").astype(str)
df_complaints['zip'].dtype

<StringDtype(storage='python', na_value=nan)>

**--> Checking missing values and matching compatibility before merging**

Checking missing values

In [21]:
# checking missing values for zip in income data 
df_income['zip'].isna().sum()
# 0 missing values!

np.int64(0)

In [22]:
# checking missing values for zip in complaints data 
df_complaints['zip'].isna().sum()
# 33451 missing values :( 

np.int64(33451)

In [23]:
df_complaints.shape

(3864047, 15)

***---> The complaints data has 33000 missing values out of 3864047 rows under column zip. ~1% of the rows in complaints data will have to be excluded from this analysis.***

Checking how many zip codes match between the two datasets

In [24]:
# checking how many unique zip codes dataset has: income data
df_income["zip"].nunique()
#1825 unique zip codes

1825

In [25]:
# checking how many unique zip codes dataset has: complaints data
df_complaints["zip"].nunique()
#352 unique zip codes

352

In [26]:
#checking how many zipcodes from complaint data are missing from income data 
income_zips = set(df_income["zip"].dropna()) #drop all missing values and give me (set) an array of unique values from this column (zip)
complaint_zips = set(df_complaints["zip"].dropna()) #ibid

missing_from_income = complaint_zips - income_zips #give an array of zips that are there in complaint zips but not in income zips

len(missing_from_income)

# for 97 zipcodes, we don't have median household income information. This is ~30% of our unique zipcode dataset (97/352)

97

In [27]:
#checking # of complaints that come from missing zips to see if these zips are a big problem 
df_complaints["zip"].isin(missing_from_income).sum()
# 2170 complaints come from missing zips.

np.int64(2170)

***---> The complaint data has 2170 complaints with 97 unique zip codes that cannot be matched with ACS income data. These zip codes, which are ~1% of the total rows in complaints data will have to be excluded from this analysis.***

### Merging datasets

In [28]:
#creating a dataframe with just what we need for merging

income_small = df_income[["zip", "median_hh_income"]].copy()
income_small

,zip,median_hh_income
0,Name,Estimate!!Median household income in the past ...
1,06390,98125
2,10001,129852
3,10002,48386
4,10003,154262
...,...,...
1820,14898,58824
1821,14901,40989
1822,14903,67012
1823,14904,53174


In [29]:
#merging

df_complaints = df_complaints.merge(
    income_small,
    on="zip",
    how="left"
)

In [30]:
# checking if it got merged properly 
df_complaints.head()

,unique_key,created_date,closed_date,agency_name,complaint,complaint_detail,complaint_add_detail,zip,city,status,resol_descrip,resol_upd_date,borough,latitude,longitude,median_hh_income
0,69197623,06/01/2026 02:07:09 PM,06/01/2026 02:16:05 PM,New York City Police Department,Illegal Parking,Blocked Sidewalk,NaN,11103,ASTORIA,Closed,The New York City Police Department responded ...,06/01/2026 02:16:08 PM,QUEENS,40.769581,-73.915593,93324
1,69207017,06/01/2026 02:07:00 PM,06/01/2026 02:07:00 PM,Department of Environmental Protection,Water System,Hydrant Running (WC3),WC3,11209,BROOKLYN,Closed,The Department of Environmental Protection det...,06/01/2026 02:07:00 PM,BROOKLYN,40.624393,-74.038340,93854
2,69205534,06/01/2026 02:06:58 PM,06/01/2026 02:06:58 PM,Department of Buildings,Building/Use,No Certificate Of Occupancy/Illegal/Contrary T...,NaN,10456,BRONX,Open,Your Service Request has been submitted to the...,06/01/2026 12:00:00 AM,BRONX,40.833781,-73.913806,34954
3,69198329,06/01/2026 02:06:52 PM,06/01/2026 02:43:43 PM,New York City Police Department,Illegal Parking,Blocked Bike Lane,NaN,11205,BROOKLYN,Closed,The New York City Police Department responded ...,06/01/2026 02:43:47 PM,BROOKLYN,40.697416,-73.956717,93887
4,69196443,06/01/2026 02:06:51 PM,06/01/2026 04:50:30 PM,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,10026,NEW YORK,Closed,The New York City Police Department responded ...,06/01/2026 04:50:33 PM,MANHATTAN,40.802451,-73.946622,81244


In [31]:
df_complaints["median_hh_income"].isna().sum()
# this sum is equal to missing values of zip code in complaint data + unmatched zip codes, the merge happened correctly.

np.int64(35621)

### Merging income + complaint merged data with population data

In [32]:
df_pop

,GEO_ID,NAME,pop,B01003_001M,Unnamed: 4
0,Geography,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,NaN
1,860Z200US06390,ZCTA5 06390,72,43,NaN
2,860Z200US10001,ZCTA5 10001,30511,1797,NaN
3,860Z200US10002,ZCTA5 10002,76873,3494,NaN
4,860Z200US10003,ZCTA5 10003,53560,2107,NaN
...,...,...,...,...,...
1820,860Z200US14898,ZCTA5 14898,1469,225,NaN
1821,860Z200US14901,ZCTA5 14901,13970,788,NaN
1822,860Z200US14903,ZCTA5 14903,7078,582,NaN
1823,860Z200US14904,ZCTA5 14904,14861,698,NaN


In [33]:
# Pop data: extract ZIP from "ZCTA5 10001" and checking adequate extraction
df_pop["zip"] = df_pop["NAME"].str.split().str[-1]
df_pop.head()

,GEO_ID,NAME,pop,B01003_001M,Unnamed: 4,zip
0,Geography,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,NaN,Name
1,860Z200US06390,ZCTA5 06390,72,43,NaN,06390
2,860Z200US10001,ZCTA5 10001,30511,1797,NaN,10001
3,860Z200US10002,ZCTA5 10002,76873,3494,NaN,10002
4,860Z200US10003,ZCTA5 10003,53560,2107,NaN,10003


**--> Ensuring data types of column zip in both datasets are same**

In [34]:
df_pop['zip'].dtype
#object

dtype('O')

In [35]:
df_complaints['zip'].dtype

dtype('O')

**--> Checking missing values and matching compatibility before merging**

Checking missing values

In [36]:
# checking how many unique zip codes dataset has: income data
df_income["zip"].nunique()
#1825 unique zip codes

1825

In [37]:
# checking missing values for zip in complaints data 
df_complaints['zip'].isna().sum()
# same as before

np.int64(33451)

Checking how many zip codes match between the two datasets

In [38]:
# checking how many unique zip codes dataset has: pop data
df_pop["zip"].nunique()
#1825 unique zip codes

1825

In [39]:
# checking how many unique zip codes dataset has: complaints data
df_complaints["zip"].nunique()
#352 unique zip codes

352

In [40]:
#checking how many zipcodes from complaint data are missing from population data 
pop_zips = set(df_pop["zip"].dropna())
complaint_zips = set(df_complaints["zip"].dropna())

missing_from_pop = complaint_zips - pop_zips #give an array of zips that are there in complaint zips but not in pop zips

len(missing_from_pop)

# for 97 zipcodes, we don't have median household income information. This is ~30% of our dataset (97/352)

97

In [41]:
#checking # of complaints that come from missing zips to see if these zips are a big problem 
df_complaints["zip"].isin(missing_from_pop).sum()
# 2170 complaints come from missing zips. So likely that it's the exact same zips missing from income data of ACS.

np.int64(2170)

### Merging datasets

In [42]:
df_pop

,GEO_ID,NAME,pop,B01003_001M,Unnamed: 4,zip
0,Geography,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,NaN,Name
1,860Z200US06390,ZCTA5 06390,72,43,NaN,06390
2,860Z200US10001,ZCTA5 10001,30511,1797,NaN,10001
3,860Z200US10002,ZCTA5 10002,76873,3494,NaN,10002
4,860Z200US10003,ZCTA5 10003,53560,2107,NaN,10003
...,...,...,...,...,...,...
1820,860Z200US14898,ZCTA5 14898,1469,225,NaN,14898
1821,860Z200US14901,ZCTA5 14901,13970,788,NaN,14901
1822,860Z200US14903,ZCTA5 14903,7078,582,NaN,14903
1823,860Z200US14904,ZCTA5 14904,14861,698,NaN,14904


In [43]:
#creating a dataframe with just what we need for merging

pop_small = df_pop[["zip", "pop"]].copy()
pop_small

,zip,pop
0,Name,Estimate!!Total
1,06390,72
2,10001,30511
3,10002,76873
4,10003,53560
...,...,...
1820,14898,1469
1821,14901,13970
1822,14903,7078
1823,14904,14861


In [44]:
df_complaints = df_complaints.merge(
    pop_small,
    on="zip",
    how="left"
)

In [45]:
# checking if it got merged properly 
df_complaints.head()

,unique_key,created_date,closed_date,agency_name,complaint,complaint_detail,complaint_add_detail,zip,city,status,resol_descrip,resol_upd_date,borough,latitude,longitude,median_hh_income,pop
0,69197623,06/01/2026 02:07:09 PM,06/01/2026 02:16:05 PM,New York City Police Department,Illegal Parking,Blocked Sidewalk,NaN,11103,ASTORIA,Closed,The New York City Police Department responded ...,06/01/2026 02:16:08 PM,QUEENS,40.769581,-73.915593,93324,35163
1,69207017,06/01/2026 02:07:00 PM,06/01/2026 02:07:00 PM,Department of Environmental Protection,Water System,Hydrant Running (WC3),WC3,11209,BROOKLYN,Closed,The Department of Environmental Protection det...,06/01/2026 02:07:00 PM,BROOKLYN,40.624393,-74.038340,93854,71004
2,69205534,06/01/2026 02:06:58 PM,06/01/2026 02:06:58 PM,Department of Buildings,Building/Use,No Certificate Of Occupancy/Illegal/Contrary T...,NaN,10456,BRONX,Open,Your Service Request has been submitted to the...,06/01/2026 12:00:00 AM,BRONX,40.833781,-73.913806,34954,87533
3,69198329,06/01/2026 02:06:52 PM,06/01/2026 02:43:43 PM,New York City Police Department,Illegal Parking,Blocked Bike Lane,NaN,11205,BROOKLYN,Closed,The New York City Police Department responded ...,06/01/2026 02:43:47 PM,BROOKLYN,40.697416,-73.956717,93887,51676
4,69196443,06/01/2026 02:06:51 PM,06/01/2026 04:50:30 PM,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,10026,NEW YORK,Closed,The New York City Police Department responded ...,06/01/2026 04:50:33 PM,MANHATTAN,40.802451,-73.946622,81244,37123


In [46]:
df_complaints["pop"].isna().sum()
# this sum is equal to missing values of zip code in complaint data + unmatched zip codes, the merge happened correctly.

np.int64(35621)

## Categorizing Income Data

In [47]:
# checking data type of income column 
df_complaints["median_hh_income"].dtype
#string

<StringDtype(storage='python', na_value=nan)>

In [48]:
# on converting this column to int, it did not convert, which means there is some values which might be like 250K +. 
df_complaints["median_hh_income"].value_counts().head(20)

median_hh_income
65969     106169
81014      60842
41288      54744
49330      53651
34954      51766
46233      51566
40800      50502
42683      49757
33186      49078
88838      48486
56523      46311
72270      45546
173136     42191
62077      41737
121062     41293
74974      39104
65895      38503
85736      38048
56829      37699
65283      37574
Name: count, dtype: int64

In [49]:
# finding odd values in income
df_complaints["median_hh_income"].unique()

<StringArray>
[ '93324',  '93854',  '34954',  '93887',  '81244', '121062', '128559',
  '38006', '123047',  '46233',
 ...
 '173281',  '97661', '124115', '157163', '103287', '173573', '142233',
 '105686', '187514',  '64776']
Length: 229, dtype: str

In [50]:
# checking odd values in income 

bad_values = df_complaints.loc[
    pd.to_numeric(df_complaints["median_hh_income"], errors="coerce").isna(), # in rows where you're unable to convert values into numeric values
    "median_hh_income"
]

bad_values.value_counts()

median_hh_income
250,000+    13138
-            7371
Name: count, dtype: int64

In [51]:
# converting 250,000+ to 250000, removing commas, and marking - as missing values 

df_complaints["median_hh_income"] = (
    df_complaints["median_hh_income"]
    .astype(str) # convert to string so str. operations can work
    .str.replace(",", "", regex=False) #removing ,
    .str.replace("+", "", regex=False) #removing +
    .replace("-", pd.NA) #pd.NA means treat this value as missing
)

df_complaints["median_hh_income"] = pd.to_numeric(
    df_complaints["median_hh_income"],
    errors="coerce"
)

In [52]:
# checking range of income column now (it is already a float)
df_complaints["median_hh_income"].describe()


# Among complaints that matched to income data:
# 25% are from ZIP codes with median household income below about $59,700.
# 50% are from ZIP codes with median household income below about $77,600.
# 75% are from ZIP codes with median household income below about $97,500.

count    3.821055e+06
mean     8.373658e+04
std      3.676683e+04
min      2.408600e+04
25%      5.966100e+04
50%      7.759800e+04
75%      9.747900e+04
max      2.500000e+05
Name: median_hh_income, dtype: float64

For deciding income categories, I should use ZIP-level income, not complaint-level income. Otherwise high-complaint ZIPs influence the cutoffs.

In [53]:
# creating dataset with only unique zip and income levels (same as our income data from ACS) to decide income categorisations:
zip_income = (
    df_complaints[["zip", "median_hh_income"]]
    .drop_duplicates()
    .dropna()
)

In [54]:
zip_income

,zip,median_hh_income
0,11103,93324.0
1,11209,93854.0
2,10456,34954.0
3,11205,93887.0
4,10026,81244.0
...,...,...
3342354,10598,173573.0
3383720,11581,142233.0
3560721,10573,105686.0
3707126,11803,187514.0


In [55]:
# Income quartiles are based on ZIP-level median household income,
# using one row per ZIP code with valid ACS income data. 
zip_income["median_hh_income"].quantile([0, 0.25, 0.5, 0.75, 1])

# Q1: $74,185
# Q2 / median: $95,345
# Q3: $127,956

0.00     24086.00
0.25     74184.75
0.50     95344.50
0.75    127955.75
1.00    250000.00
Name: median_hh_income, dtype: float64

In [56]:
# Lowest income:       $24,086 – $74,185
# Lower-middle income: $74,185 – $95,345
# Upper-middle income: $95,345 – $127,956
# Highest income:      $127,956 – $250,000

In [57]:
bins = [0, 74184.75, 95344.50, 127955.75, 250000]

labels = [
    "Lowest income",
    "Lower-middle income",
    "Upper-middle income",
    "Highest income"
]

df_complaints["income_category"] = pd.cut(
    df_complaints["median_hh_income"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [58]:
df_complaints["income_category"].value_counts(normalize=True, dropna=False)*100

income_category
Lowest income          45.833940
Lower-middle income    25.348268
Upper-middle income    14.626427
Highest income         13.078749
NaN                     1.112616
Name: proportion, dtype: float64

Most complaints in my matched dataset come from ZIPs in the lowest income quartile. But that could be because:
- lower-income ZIPs have more people,
- lower-income ZIPs have more 311-reportable problems,
- lower-income residents complain more

In [59]:
df_complaints.head(5)

,unique_key,created_date,closed_date,agency_name,complaint,complaint_detail,complaint_add_detail,zip,city,status,resol_descrip,resol_upd_date,borough,latitude,longitude,median_hh_income,pop,income_category
0,69197623,06/01/2026 02:07:09 PM,06/01/2026 02:16:05 PM,New York City Police Department,Illegal Parking,Blocked Sidewalk,NaN,11103,ASTORIA,Closed,The New York City Police Department responded ...,06/01/2026 02:16:08 PM,QUEENS,40.769581,-73.915593,93324.0,35163,Lower-middle income
1,69207017,06/01/2026 02:07:00 PM,06/01/2026 02:07:00 PM,Department of Environmental Protection,Water System,Hydrant Running (WC3),WC3,11209,BROOKLYN,Closed,The Department of Environmental Protection det...,06/01/2026 02:07:00 PM,BROOKLYN,40.624393,-74.038340,93854.0,71004,Lower-middle income
2,69205534,06/01/2026 02:06:58 PM,06/01/2026 02:06:58 PM,Department of Buildings,Building/Use,No Certificate Of Occupancy/Illegal/Contrary T...,NaN,10456,BRONX,Open,Your Service Request has been submitted to the...,06/01/2026 12:00:00 AM,BRONX,40.833781,-73.913806,34954.0,87533,Lowest income
3,69198329,06/01/2026 02:06:52 PM,06/01/2026 02:43:43 PM,New York City Police Department,Illegal Parking,Blocked Bike Lane,NaN,11205,BROOKLYN,Closed,The New York City Police Department responded ...,06/01/2026 02:43:47 PM,BROOKLYN,40.697416,-73.956717,93887.0,51676,Lower-middle income
4,69196443,06/01/2026 02:06:51 PM,06/01/2026 04:50:30 PM,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,10026,NEW YORK,Closed,The New York City Police Department responded ...,06/01/2026 04:50:33 PM,MANHATTAN,40.802451,-73.946622,81244.0,37123,Lower-middle income


#### Dropping missing values from income column

In [60]:
df_complaints['income_category'].isna().sum()

np.int64(42992)

In [61]:
df_complaints.shape
# 1% of rows have income rows missing, we will drop it

(3864047, 18)

In [62]:
# dropping values for income column and creating new dataset

df_complaints_clean = df_complaints.dropna(
    subset=["income_category"]
).copy()

In [63]:
# checking drop happened adequately
df_complaints_clean.shape

(3821055, 18)

### Checking which zip codes don't match new york zip codes (problem seen while inputting data in datawrapper):

## Cleaning Complaints

In [64]:
# checking % of complaints in all of new york
complaints_nyc = (df_complaints_clean['complaint'].value_counts(normalize=True)*100).head(30)
complaints_nyc

complaint
Illegal Parking                  15.631625
Noise - Residential              11.282172
HEAT/HOT WATER                    9.303635
Blocked Driveway                  4.938374
Noise - Street/Sidewalk           4.568293
UNSANITARY CONDITION              3.322302
Street Condition                  2.744190
Water System                      2.265186
PLUMBING                          2.056997
Abandoned Vehicle                 1.801256
Dirty Condition                   1.757525
PAINT/PLASTER                     1.678385
Snow or Ice                       1.666843
Noise - Commercial                1.598459
Noise                             1.520392
Traffic Signal Condition          1.343556
DOOR/WINDOW                       1.305529
Noise - Vehicle                   1.225159
Encampment                        1.185955
WATER LEAK                        1.125003
GENERAL                           0.980933
Illegal Dumping                   0.977976
Missed Collection                 0.975673
G

In [65]:
complaints_nyc.cumsum()

complaint
Illegal Parking                  15.631625
Noise - Residential              26.913797
HEAT/HOT WATER                   36.217432
Blocked Driveway                 41.155806
Noise - Street/Sidewalk          45.724100
UNSANITARY CONDITION             49.046402
Street Condition                 51.790592
Water System                     54.055778
PLUMBING                         56.112775
Abandoned Vehicle                57.914032
Dirty Condition                  59.671557
PAINT/PLASTER                    61.349941
Snow or Ice                      63.016785
Noise - Commercial               64.615244
Noise                            66.135635
Traffic Signal Condition         67.479191
DOOR/WINDOW                      68.784720
Noise - Vehicle                  70.009879
Encampment                       71.195835
WATER LEAK                       72.320838
GENERAL                          73.301771
Illegal Dumping                  74.279747
Missed Collection                75.255420
G

#### exploring complaints

##### Unsanitary condition

In [66]:
#What is unsanitary condition?
df_complaints_clean[df_complaints_clean['complaint'] == 'UNSANITARY CONDITION'].value_counts('complaint_detail')

complaint_detail
PESTS                        66469
MOLD                         36479
GARBAGE/RECYCLING STORAGE    20060
SEWAGE                        3939
Name: count, dtype: int64

In [67]:
(df_complaints_clean[df_complaints_clean['complaint'] == 'UNSANITARY CONDITION'].value_counts('complaint_add_detail', normalize=True)*100).cumsum().head(50)

complaint_add_detail
MICE                               30.504709
ROACHES                            58.160897
ACCUMULATION                       72.214485
OTHER                              80.951276
MISSING OR INADEQUATE CANS/LID     89.071274
BED BUGS                           92.187293
RAW SEWAGE ACCUMULATION            94.902065
FLIES                              97.550515
BROKEN/BLOCKED SEWAGE PIPE         99.189769
TERMITES                           99.650705
FLEAS                             100.000000
Name: proportion, dtype: float64

In [68]:
# Unsanitary condition refers to pests, mold, garbage/recycling storage, and sewage
# Within this, 30% are mice, 27% are roaches, 14% is accumulation, 8% is other - these cover 80% of all complaints within unsanitary conditions.

##### dirty condition

In [69]:
#What is dirty condition?

df_complaints_clean[df_complaints_clean['complaint'] == 'Dirty Condition'].value_counts('complaint_detail', normalize=True)*100

complaint_detail
Trash                       88.970457
Dog Waste                    5.555721
Dirt or Gravel               1.937280
Broken Glass                 1.675204
Syringes                     1.229972
Debris from Car Accident     0.631366
Name: proportion, dtype: float64

In [70]:
(df_complaints_clean[df_complaints_clean['complaint'] == 'Dirty Condition'].value_counts('complaint_add_detail', normalize=True)*100)

complaint_add_detail
Littering                        58.029301
Not Cleaned by Property Owner    39.187146
Not Picked Up by Dog Owner        2.783554
Name: proportion, dtype: float64

In [71]:
# dirty condition refers to trash (~90%) of this category, followed by dog waste (5%), dirt/gravel (1%), broken glass (1%), syringes, debris from car accident.
# within this, ~60% report someone is littering, 40% say that dog waste/trash was not cleaned by property owner, 2% say poop not picked up by dog owner

##### street condition

In [72]:
#What is Street Condition?

df_complaints_clean[df_complaints_clean['complaint'] == 'Street Condition'].value_counts('complaint_detail', normalize=True)*100

complaint_detail
Pothole                           63.326244
Cave-in                           12.917593
Defective Hardware                 5.909000
Blocked - Construction             4.166627
Failed Street Repair               3.988289
Rough, Pitted or Cracked Roads     3.773711
Plate Condition - Noisy            2.629295
Plate Condition - Shifted          0.653271
Dumpster - Construction Waste      0.615123
Line/Marking - Faded               0.596050
Line/Marking - After Repaving      0.582698
Wear & Tear                        0.265123
Crash Cushion Defect               0.151635
Guard Rail - Street                0.123025
Depression Maintenance             0.106812
Unsafe Worksite                    0.071526
Plate Condition - Open             0.061989
Plate Condition - Anti-Skid        0.032425
Defacement                         0.016213
Hummock                            0.011444
Maintenance Cover                  0.001907
Name: proportion, dtype: float64

In [73]:
(df_complaints_clean[df_complaints_clean['complaint'] == 'Street Condition'].value_counts('complaint_add_detail', normalize=True)*100)

complaint_add_detail
Other    100.0
Name: proportion, dtype: float64

In [74]:
# when people complain about street condition, 63% are referring to potholes,12% are referring to cave-ins, 5% to defective hardware etc. All related to actual street. 

#### heat/hot water

In [75]:
#What is heat/hot water?

df_complaints_clean[df_complaints_clean['complaint'] == 'HEAT/HOT WATER'].value_counts('complaint_detail', normalize=True)*100

complaint_detail
ENTIRE BUILDING    65.757517
APARTMENT ONLY     34.242483
Name: proportion, dtype: float64

In [76]:
(df_complaints_clean[df_complaints_clean['complaint'] == 'HEAT/HOT WATER'].value_counts('complaint_add_detail', normalize=True)*100)

complaint_add_detail
NO HEAT                     59.552964
NO HEAT AND NO HOT WATER    25.791498
NO HOT WATER                14.437815
HEAT ON IN SUMMER            0.217723
Name: proportion, dtype: float64

In [77]:
# when people complaint about heat/hot water, 65% say they're not getting heat/hot water in entire building and 34% say in apartment only.

##### Water System

In [78]:
#What is Water System?

(df_complaints_clean[df_complaints_clean['complaint'] == 'Water System'].value_counts('complaint_detail', normalize=True)*100).cumsum()

complaint_detail
Hydrant Running Full (WA4)                         15.735841
Hydrant Running (WC3)                              31.387342
Dirty Water (WE)                                   44.701574
Fire Hydrant Emergency (FHE)                       57.849435
Leak (Use Comments) (WA2)                          70.053377
Hydrant Leaking (WC1)                              77.670587
Possible Water Main Break (Use Comments) (WA1)     84.834901
No Water (WNW)                                     90.953624
Hydrant Defective (WC2)                            94.036093
LOW WATER PRESSURE - WLWP                          96.037156
Hydrant Knocked Over/Missing (WC)                  97.963121
Excessive Water In Basement (WEFB)                 99.406151
Hyd Valve Box Cover Missing (WV2)                  99.844028
installation of hydrant side post (WHFP)           99.951475
High Water Pressure (WHP)                         100.000000
Name: proportion, dtype: float64

In [79]:
# when people complaint about water system, 
# it is related to largely water hydrant, fire hydrant, water breakage, low water pressure, dirty water

#### plumbing

In [80]:
#What is Plumbing and how is it different from water system?

(df_complaints_clean[df_complaints_clean['complaint'] == 'PLUMBING'].value_counts('complaint_detail', normalize=True)*100)

complaint_detail
WATER SUPPLY        32.906271
BASIN/SINK          23.958320
BATHTUB/SHOWER      20.046057
TOILET              13.703737
RADIATOR             6.659118
STEAM PIPE/RISER     2.461863
SEWER                0.132317
BOILER               0.132317
Name: proportion, dtype: float64

In [81]:
(df_complaints_clean[df_complaints_clean['complaint'] == 'PLUMBING'].value_counts('complaint_add_detail', normalize=True)*100)

complaint_add_detail
NO WATER                          22.479930
FAUCET BROKEN/MISSING/LEAKING     10.850011
BROKEN OR MISSING                  9.262204
DRAIN PIPE BLOCKED OR BROKEN       6.577692
NO HOT WATER                       5.610758
CHIPPED OR RUSTED                  5.090396
BASIN BROKEN/LEAKING               4.430082
PIPE LEAKING                       4.244329
LOW WATER PRESSURE                 4.011501
BOWL STOPPED UP                    3.751956
CRACKED OR LEAKING                 2.243031
BOWL CRACKED OR LEAKING            2.173056
SCALDING HOT WATER                 2.087813
CONTINUOUSLY RUNS                  1.744297
SINK DETACHED FROM WALL            1.730302
FLUSH HANDLE BROKEN OR MISSING     1.703584
LEAKING INTO OTHER APARTMENT       1.661599
BOWL LOOSE OR WOBBLY               1.302816
TANK CRACKED OR LEAKING            1.291365
CRACKED OR BROKEN                  1.251924
LEAKING                            1.209939
BASIN CHIPPED OR RUSTED            0.994924
NO COLD WAT

In [82]:
# When people complain about plumbing, 30% are referring to water supply (unclear how it is different from water system in some places),
#23% are telling us that plumbing of basin / sink is broken, 20% say plumbing of bathtub/shower is broken, 13% say plumbing of toilet is
# broken. Other smaller categories include radiator, steam pipe, sewer, boiler

##### paint/plaster

In [83]:
#What is PAINT/PLASTER?

df_complaints_clean[df_complaints_clean['complaint'] == 'PAINT/PLASTER'].value_counts('complaint_detail', normalize=True)*100

complaint_detail
WALL            48.857045
CEILING         45.390757
WINDOW/FRAME     1.627892
RADIATOR         1.540573
DOOR/FRAME       1.392441
CABINET          1.191293
Name: proportion, dtype: float64

In [84]:
df_complaints_clean[df_complaints_clean['complaint'] == 'PAINT/PLASTER'].value_counts('complaint_add_detail', normalize=True)*100

complaint_add_detail
CHIPPED/PEELING/FLAKING     28.138839
BULGING/HOLE/CRACKED        19.534710
COLLAPSING OR FALLING       18.692696
HOLE OR CRACKED             15.291898
DIRTY OR UNSANITARY          9.815693
PEELING OR FLAKING PAINT     5.752199
TILE BROKEN OR MISSING       2.773966
Name: proportion, dtype: float64

In [85]:
# paint/plaster refers to paint/plaster on wall or ceilinng (dominantly) chipping off, cracked/creating hole, collapsing or falling, 
# dirty or unsanitary. 

#### Sewer

In [86]:
df_complaints_clean[df_complaints_clean['complaint'] == 'Sewer'].value_counts('complaint_detail', normalize=True)*100

complaint_detail
Sewer Backup (Use Comments) (SA)                    29.874933
Catch Basin Clogged/Flooding (Use Comments) (SC)    25.127757
Street Flooding (SJ)                                14.177649
Catch Basin Search (SC2)                             5.927246
Catch Basin Sunken/Damaged/Raised (SC1)              4.995966
Sewer Odor (SA2)                                     4.858123
Manhole Cover Missing (Emergency) (SA3)              4.753900
Manhole Overflow (Use Comments) (SA1)                3.963825
Culvert Blocked/Needs Cleaning (SE)                  2.245831
RAIN GARDEN DEBRIS (GIRGD)                           1.472566
Defective/Missing Curb Piece (SC4)                   1.042227
Catch Basin Grating Missing (SA4)                    0.746369
RAIN GARDEN PLANTING (GIRGP)                         0.460597
RAIN GARDEN STRUCTURE (GIRGS)                        0.329478
Highway Flooding (SH)                                0.020172
RAIN GARDEN FLOODING (SRGFLD)                        

In [87]:
#making broader buckets for complaints

def group_complaints(complaint):
    
    if complaint in [
        "Noise - Residential",
        "Noise - Street/Sidewalk",
        "Noise - Commercial",
        "Noise",
        "Noise - Vehicle"
    ]:
        return "noise"

    elif complaint in [
        "HEAT/HOT WATER",
        "Water System",
        "PLUMBING",
        "WATER LEAK",
        "Sewer"
    ]:
        return "drainage, water and plumbing"

    elif complaint in [
        "UNSANITARY CONDITION",
        "Dirty Condition",
        "Illegal Dumping",
        "Missed Collection"
    ]:
        return "dirty or unsanitary conditions"

    elif complaint in [
        "Illegal Parking",
        "Blocked Driveway",
        "Abandoned Vehicle",
        "Derelict Vehicles"
    ]:
        return "parking and vehicles"

    else:
        return complaint.lower()

- noise:
Combines residential noise, street/sidewalk noise, commercial noise, vehicle noise, and general noise complaints. These all refer to unwanted sound disturbances, even though the source differs.

- housing, water and plumbing:
Combines HEAT/HOT WATER, Water System, PLUMBING, WATER LEAK, and Sewer. These categories all relate to basic housing infrastructure and water-related service failures. The grouping is broad, but useful because hot water, water supply, leaks, plumbing, and sewer issues overlap in lived experience.

- dirty or unsanitary conditions:
Combines UNSANITARY CONDITION, Dirty Condition, Illegal Dumping, and Missed Collection. These categories all relate to trash, pests, mold, garbage, dumping, waste removal, or unsanitary physical conditions. They are combined because they describe cleanliness/sanitation problems in buildings or public space.

- parking and vehicles:
Combines Illegal Parking, Blocked Driveway, Abandoned Vehicle, and Derelict Vehicles. These all relate to vehicle storage, obstruction, or improper vehicle use in public/private space.

In [88]:
#applying buckets to dataset
df_complaints_clean["complaint_group"] = df_complaints_clean["complaint"].apply(group_complaints)

In [89]:
#checking adequate conversion 
df_complaints_clean.head()

,unique_key,created_date,closed_date,agency_name,complaint,complaint_detail,complaint_add_detail,zip,city,status,resol_descrip,resol_upd_date,borough,latitude,longitude,median_hh_income,pop,income_category,complaint_group
0,69197623,06/01/2026 02:07:09 PM,06/01/2026 02:16:05 PM,New York City Police Department,Illegal Parking,Blocked Sidewalk,NaN,11103,ASTORIA,Closed,The New York City Police Department responded ...,06/01/2026 02:16:08 PM,QUEENS,40.769581,-73.915593,93324.0,35163,Lower-middle income,parking and vehicles
1,69207017,06/01/2026 02:07:00 PM,06/01/2026 02:07:00 PM,Department of Environmental Protection,Water System,Hydrant Running (WC3),WC3,11209,BROOKLYN,Closed,The Department of Environmental Protection det...,06/01/2026 02:07:00 PM,BROOKLYN,40.624393,-74.038340,93854.0,71004,Lower-middle income,"drainage, water and plumbing"
2,69205534,06/01/2026 02:06:58 PM,06/01/2026 02:06:58 PM,Department of Buildings,Building/Use,No Certificate Of Occupancy/Illegal/Contrary T...,NaN,10456,BRONX,Open,Your Service Request has been submitted to the...,06/01/2026 12:00:00 AM,BRONX,40.833781,-73.913806,34954.0,87533,Lowest income,building/use
3,69198329,06/01/2026 02:06:52 PM,06/01/2026 02:43:43 PM,New York City Police Department,Illegal Parking,Blocked Bike Lane,NaN,11205,BROOKLYN,Closed,The New York City Police Department responded ...,06/01/2026 02:43:47 PM,BROOKLYN,40.697416,-73.956717,93887.0,51676,Lower-middle income,parking and vehicles
4,69196443,06/01/2026 02:06:51 PM,06/01/2026 04:50:30 PM,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,10026,NEW YORK,Closed,The New York City Police Department responded ...,06/01/2026 04:50:33 PM,MANHATTAN,40.802451,-73.946622,81244.0,37123,Lower-middle income,noise


In [90]:
# checking if no major category got left out 
complaints_nyc = (df_complaints_clean['complaint_group'].value_counts(normalize=True)*100).head(30)

In [91]:
complaints_nyc

complaint_group
parking and vehicles              23.320784
noise                             20.194475
drainage, water and plumbing      15.529245
dirty or unsanitary conditions     7.033476
street condition                   2.744190
paint/plaster                      1.678385
snow or ice                        1.666843
traffic signal condition           1.343556
door/window                        1.305529
encampment                         1.185955
general                            0.980933
general construction/plumbing      0.970936
street light condition             0.877716
electric                           0.876695
damaged tree                       0.873319
homeless person assistance         0.859318
flooring/stairs                    0.760916
rodent                             0.718466
maintenance or facility            0.700854
vendor enforcement                 0.700199
sidewalk condition                 0.685517
elevator                           0.677195
non-emergency po

In [92]:
# saving dataset 
df_complaints_clean.to_csv("complaints_with_income.csv", index=False)